import { SignatureState, TemplateArchetype } from './types';

export const INITIAL_SIGNATURE_STATE: SignatureState = {
  template: 'classic',
  canvasMode: 'desktop',
  isDarkCanvas: false,
  spacingPreset: 'normal',
  socialIconSize: 20,
  activeStep: 3,
  personal: {
    firstName: 'John',
    lastName: 'Doe',
    jobTitle: 'Sales & Marketing Director',
    department: 'Enterprise Strategy',
    email: 'john.doe@my-company.com',
    phone: '(800) 555-0199',
    mobile: '(800) 555-0299',
    pronouns: 'He / Him',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=240&q=80',
  },
  company: {
    name: 'SignatureCraft Enterprise',
    website: 'www.signaturecraft.io',
    address1: '350 Fifth Avenue',
    address2: 'Suite 4800',
    city: 'New York',
    state: 'NY',
    zip: '10118',
    tagline: 'Precision Mail Formatting Engine & Global Brand Governance',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=200&q=80',
  },
  style: {
    colorH1: '#002956',
    colorH2: '#006783',
    colorBody: '#0b1c30',
    colorLink: '#006783',
    colorAccent: '#57d1fe',
    colorBg: '#ffffff',
    fontFamily: 'Arial, sans-serif',
    nameFontSize: 18,
    baseFontSize: 13,
    toggles: {
      avatar: true,
      logo: true,
      department: true,
      phone: true,
      mobile: true,
      address: true,
      tagline: true,
      social: true,
      disclaimer: true,
      calendar: true,
      divider: true,
      pronouns: true,
    },
    calendarUrl: 'https://calendly.com/john-doe-demo/30min',
    calendarLabel: '📅 Schedule a 15-min discovery call',
    disclaimer: 'The content of this email is confidential and intended solely for the recipient specified. If you received this in error, please notify the sender immediately and delete it.',
  },
  socials: [
    { id: 'linkedin', name: 'LinkedIn', active: true, url: 'https://linkedin.com/in/johndoe', label: 'in', brandColor: '#002956' },
    { id: 'x', name: 'X Corp', active: true, url: 'https://x.com/johndoe', label: '𝕏', brandColor: '#002956' },
    { id: 'github', name: 'GitHub', active: true, url: 'https://github.com/johndoe', label: 'git', brandColor: '#002956' },
    { id: 'youtube', name: 'YouTube', active: true, url: 'https://youtube.com/@johndoe', label: 'yt', brandColor: '#ba1a1a' },
    { id: 'facebook', name: 'Facebook', active: false, url: 'https://facebook.com/johndoe', label: 'f', brandColor: '#002956' },
    { id: 'instagram', name: 'Instagram', active: false, url: 'https://instagram.com/johndoe', label: 'ig', brandColor: '#57d1fe' },
    { id: 'whatsapp', name: 'WhatsApp', active: false, url: 'https://wa.me/18005550199', label: 'wa', brandColor: '#006783' },
    { id: 'discord', name: 'Discord', active: false, url: 'https://discord.gg/brand', label: 'dc', brandColor: '#173f73' },
    { id: 'tiktok', name: 'TikTok', active: false, url: 'https://tiktok.com/@brand', label: 'tt', brandColor: '#0b1c30' },
    { id: 'pinterest', name: 'Pinterest', active: false, url: 'https://pinterest.com/brand', label: 'p', brandColor: '#ffdad6' },
    { id: 'spotify', name: 'Spotify', active: false, url: 'https://spotify.com/show/brand', label: 'sp', brandColor: '#006783' },
    { id: 'telegram', name: 'Telegram', active: false, url: 'https://t.me/brandchannel', label: 'tg', brandColor: '#57d1fe' },
    { id: 'snapchat', name: 'Snapchat', active: false, url: 'https://snapchat.com/add/brand', label: 'sc', brandColor: '#d3e4fe' },
    { id: 'signal', name: 'Signal', active: false, url: 'https://signal.me/#p/brand', label: 'sg', brandColor: '#002956' },
    { id: 'reddit', name: 'Reddit', active: false, url: 'https://reddit.com/r/brand', label: 'rd', brandColor: '#ffdad6' },
    { id: 'twitch', name: 'Twitch', active: false, url: 'https://twitch.tv/brand', label: 'tw', brandColor: '#003797' },
  ],
};

export const TEMPLATES_CONFIG: Array<{
  id: TemplateArchetype;
  name: string;
  description: string;
  badgeText: string;
}> = [
  {
    id: 'classic',
    name: 'Classic Corporate',
    description: 'Vertical accent bar & side-by-side photo layout.',
    badgeText: 'Popular',
  },
  {
    id: 'minimal',
    name: 'Modern Minimal',
    description: 'Clean horizontal hierarchy with compact footer.',
    badgeText: 'Clean',
  },
  {
    id: 'corporate-logo',
    name: 'Brand & Logo',
    description: 'Emphasis on dual personal photo + corporate emblem.',
    badgeText: 'Branded',
  },
  {
    id: 'social',
    name: 'Photo + Social',
    description: 'Prominent circular avatar with dedicated badge strip.',
    badgeText: 'Dynamic',
  },
  {
    id: 'executive',
    name: 'Executive Suite',
    description: 'Refined serif typography, dual contact columns & notices.',
    badgeText: 'Executive',
  },
];

export const PRESET_AVATARS = {
  executive: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=240&q=80',
  creative: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=240&q=80',
};

export const PRESET_LOGOS = {
  tech: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=200&q=80',
  crest: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=200&q=80',
};

export const SAMPLE_PROFILES = [
  {
    id: 'sales-director',
    label: 'Sales & Marketing Director',
    roleTag: 'Commercial',
    personal: {
      firstName: 'John',
      lastName: 'Doe',
      jobTitle: 'Sales & Marketing Director',
      department: 'Enterprise Strategy',
      email: 'john.doe@my-company.com',
      phone: '(800) 555-0199',
      mobile: '(800) 555-0299',
      pronouns: 'He / Him',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=240&q=80',
    },
    company: {
      name: 'SignatureCraft Enterprise',
      website: 'www.signaturecraft.io',
      address1: '350 Fifth Avenue',
      address2: 'Suite 4800',
      city: 'New York',
      state: 'NY',
      zip: '10118',
      tagline: 'Precision Mail Formatting Engine & Global Brand Governance',
      logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=200&q=80',
    },
    template: 'classic' as TemplateArchetype,
  },
  {
    id: 'tech-founder',
    label: 'CTO & Co-Founder',
    roleTag: 'Engineering',
    personal: {
      firstName: 'Sarah',
      lastName: 'Chen',
      jobTitle: 'Chief Technology Officer',
      department: 'Platform Architecture',
      email: 's.chen@cloudpulse.tech',
      phone: '+1 (415) 890-2341',
      mobile: '+1 (415) 720-9118',
      pronouns: 'She / Her',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=240&q=80',
    },
    company: {
      name: 'CloudPulse Systems Inc.',
      website: 'www.cloudpulse.tech',
      address1: '540 Howard Street',
      address2: 'Floor 3',
      city: 'San Francisco',
      state: 'CA',
      zip: '94105',
      tagline: 'High-Throughput Distributed Microservices for Modern Teams',
      logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=200&q=80',
    },
    template: 'minimal' as TemplateArchetype,
  },
  {
    id: 'legal-partner',
    label: 'Managing Legal Counsel',
    roleTag: 'Legal / Finance',
    personal: {
      firstName: 'Alexander',
      lastName: 'Sterling',
      jobTitle: 'Senior Managing Partner',
      department: 'Corporate M&A Practice',
      email: 'a.sterling@sterlingvance.com',
      phone: '+1 (212) 993-4100',
      mobile: '+1 (917) 442-8800',
      pronouns: 'He / Him',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=240&q=80',
    },
    company: {
      name: 'Sterling & Vance LLP',
      website: 'www.sterlingvance.com',
      address1: '1221 Avenue of the Americas',
      address2: '36th Floor',
      city: 'New York',
      state: 'NY',
      zip: '10020',
      tagline: 'Strategic Legal Advisory & Cross-Border Transactions',
      logoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=200&q=80',
    },
    template: 'executive' as TemplateArchetype,
  },
];
